services:
  - type: web
    name: descargar-musica-api
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
